[package]
name = "turbine-simulation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
rand_chacha = "0.2.2"
statistical = "1.0.0"
clap = "2.33.1"
